---
- name: Install PHP stack
  block:
    - name: Add PHP repo
      ansible.builtin.apt_repository:
        repo: "ppa:ondrej/php"
        state: present
    
    - name: Install PHP and extensions
      ansible.builtin.apt:
        name: "{{ php_packages }}"
        state: present
        update_cache: yes
    
    - name: Install Composer
      ansible.builtin.get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php
    
    - name: Run Composer install
      ansible.builtin.command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
      args:
        creates: /usr/local/bin/composer
    
    - name: Cleanup Composer installer
      ansible.builtin.file:
        path: /tmp/composer-setup.php
        state: absent
  tags: [php, install]