plugin: aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: running
  tag:Environment: jenkins
  tag:Role: jenkins
keyed_groups:
  - key: tags.Role
    prefix: aws_Role
compose:
  ansible_host: public_ip_address