---
- name: restart postgresql
  ansible.builtin.service:
    name: postgresql
    state: restarted

- name: restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: yes

- name: restart jenkins
  ansible.builtin.systemd:
    name: jenkins
    state: restarted